@server=http://localhost:8080

###
GET {{server}}/odata/v4/BooksService/Books

###
POST {{server}}/odata/v4/BooksService/createBook
Content-Type: application/json

{
    "book": {
        "ID": 11,
        "title": "My Test",
        "stock": 99
    }
}

### 
POST {{server}}/odata/v4/BooksService/Books(1)/BooksService.updateStock
Content-Type: application/json

{
    "stock": 7
}