
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false

---  
spring:
  config.activate.on-profile: cloud
  sql.init.schema-locations: classpath:schema-nomocks.sql
cds:
  remote.services:
    CatalogService:
      destination:
        type: "odata-v4"

---
spring:
  config.activate.on-profile: mocked
cds:
  application.services:
    CatalogService-mocked:
      model: CatalogService
      serve:
        path: CatalogService
  remote.services:
    CatalogService:
      destination:
        name: "catalogservice-mocked"
        suffix: "/odata/v4"    

---
logging:
  level:
    root: DEBUG        